FROM 0xpolygon/polygon-edge:latest

RUN polygon-edge secrets init --data-dir data-dir

COPY genesis.json .

COPY run.sh .

# Node.js and Staking
RUN apk add --update npm
RUN apk add --no-cache git
RUN mkdir staking && cd ./staking && git clone https://github.com/R-Santev/staking-contracts.git && cd ./staking-contracts && git checkout scale && npm install
ENV JSONRPC_URL=http://localhost:10002
ENV STAKING_CONTRACT_ADDRESS=0x0000000000000000000000000000000000001001
ENV MAX_VALIDATOR_COUNT=500
ENV MIN_VALIDATOR_COUNT=2

ENV MAIN_NODE_KEY=243bd03210350fb5f0345d28a08ab1a329d7318874b9f5f5d0f7e8736eeb364d

# ARG GRPC_PORT
# ENV GRPC_PORT=$GRPC_PORT

# ARG LIBP2P_PORT
# ENV LIBP2P_PORT=$LIBP2P_PORT

# ARG JSONRPC_PORT
# ENV JSONRPC_PORT=$JSONRPC_PORT

RUN cd ./../..

COPY staking.sh .
RUN /staking.sh

RUN cd ./staking/staking-contracts npm run build && npm run fund_node && npm run stake && npm run register-blskey

EXPOSE 10000 10001 10002
ENTRYPOINT "./run.sh"
