FROM 0xpolygon/polygon-edge:latest

RUN polygon-edge secrets init --data-dir data-dir

COPY genesis.json genesis.json 

COPY test.sh test.sh

# Node.js and Staking
RUN apk add --update npm
RUN apk add --no-cache git
RUN mkdir staking && cd ./staking && git clone https://github.com/R-Santev/staking-contracts.git && cd ./staking-contracts && git checkout scale && npm install
ENV JSONRPC_URL=http://localhost:10002
ENV STAKING_CONTRACT_ADDRESS=0x0000000000000000000000000000000000001001
ENV MAX_VALIDATOR_COUNT=500
ENV MIN_VALIDATOR_COUNT=2

ARG MAIN_NODE_KEY_ARG
ENV MAIN_NODE_KEY=$MAIN_NODE_KEY_ARG

RUN cd ./../..

COPY ./staking.sh ./staking.sh
RUN /staking.sh

RUN cd ./staking/staking-contracts npm run build && npm run fund_node && npm run stake && npm run register-blskey

RUN cd ./../..

COPY ./check.sh ./check.sh
RUN /check.sh

EXPOSE 30000 30001 30002
ENTRYPOINT "./test.sh"
