version: "3.9"
services:
  bootnode-one:
    # hostname: 'bootnode'
    build:
      context: .
      dockerfile: ./bootnodes/Dockerfile.boot
      args:
        BOOTNODE_FOLDER: bootnode-one
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    # deploy:
    #   mode: global
  bootnode-two:
    # hostname: 'bootnode'
    build:
      context: .
      dockerfile: ./bootnodes/Dockerfile.boot
      args:
        BOOTNODE_FOLDER: bootnode-two
    ports:
      - "20000:10000"
      - "20001:10001"
      - "20002:10002"
    # deploy:
    #   mode: global
  tx-executor:
    image: rsantev/edge-tx-executor:latest
    ports:
      - "5000:5000"
    environment:
      - BOOTNODE_KEY=bbdf1dc839add5c303231df3a9aaa862299f0bb66e5a614cc5b284abcc3297ad
      - PROVIDER_URL=http://bootnode-one:10002
    depends_on:
      - bootnode-one
      - bootnode-two
  nodes:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    ports:
      - "10000"
      - "10001"
      - "10002"
    deploy:
      mode: replicated
      replicas: 3
      # endpoint_mode: vip
      # resources:
      #   limits:
      #     cpus: '0.50'
      #     memory: 50M
    depends_on:
      - tx-executor
